Fix choco pack syntax
Use --version instead of $currentVersion$ which is no longer recognized by choco 2.0.0.

Was getting this error:
ERROR: CHCU0001: '$currentVersion$' is not a valid version string in the package nuspec file.